import type { PdfTheme } from "./types";

export const BUILTIN_THEMES: PdfTheme[] = [
  {
    id: "minimal",
    name: "Minimal",
    builtin: true,
    primaryColor: "#222222",
    accentColor: "#555555",
    logoPath: "",
    showCover: false,
    showToc: false,
    tocTitle: "Table of Contents",
    title: "",
    subtitle: "",
    additionalContent: "",
    coverBackgroundPath: "",
    coverImagePath: "",
    coverImageWidth: "",
    coverInfoFields: [],
    protocolLike: false,

    showHeaderLogo: false,
    headerLogoHeight: "10mm",
    headerText: "",
    headerText2: "",
    showPagination: true,
    paginationFormat: "{page} / {pages}",
    footerText: "",
    urlDisplay: "off",
    numberHeadings: false,
    showLegal: false,
    legalTitle: "",
    legalText: "",
    legalCompany: "",
    legalDepartment1: "",
    legalDepartment2: "",
    legalStreet: "",
    legalCity: "",
    legalTelephone: "",
    legalMail: "",
    legalWebLink: "",
    legalWebLinkAlt: "",
    legalEditorial: "",
    legalAuthor: "",
    legalPhotoCredit: "",
    bodyFont: "'Georgia', 'Times New Roman', serif",
    codeFont: "'SF Mono', 'Fira Code', monospace",
    bodyFontSize: "11pt",
    customFonts: [],
    pageSize: "A4",
    orientation: "portrait",
    margins: { top: "20mm", right: "20mm", bottom: "20mm", left: "20mm" },
    pageBreakBeforeH1: false,
    pageBreakBeforeH2: false,
    pageBreakBeforeH3: false,
    includeMetadata: false,
    classificationText: "",
    classificationColor: "#c0392b",
    watermarkText: "",
    watermarkColor: "#000000",
    watermarkOpacity: 0.08,
    watermarkFontSize: "80pt",
    watermarkRotation: -45,
  },
];

/**
 * Deep-copy a theme into a new custom one. Deep, because `margins` and
 * `coverInfoFields` would otherwise be shared with the source theme and mutate
 * it from the editor.
 */
export function duplicateTheme(theme: PdfTheme): PdfTheme {
  const copy = JSON.parse(JSON.stringify(theme)) as PdfTheme;
  copy.id = "custom-" + Date.now();
  copy.name = `${theme.name} (copy)`;
  delete copy.builtin;
  return copy;
}

export function createBlankTheme(): PdfTheme {
  return {
    id: "custom-" + Date.now(),
    name: "New theme",
    primaryColor: "#333333",
    accentColor: "#666666",
    logoPath: "",
    showCover: true,
    showToc: false,
    tocTitle: "Table of Contents",
    title: "",
    subtitle: "",
    additionalContent: "",
    coverBackgroundPath: "",
    coverImagePath: "",
    coverImageWidth: "",
    coverInfoFields: [],
    protocolLike: false,

    showHeaderLogo: false,
    headerLogoHeight: "12mm",
    headerText: "",
    headerText2: "",
    showPagination: true,
    paginationFormat: "{page} / {pages}",
    footerText: "",
    urlDisplay: "off",
    numberHeadings: false,
    showLegal: false,
    legalTitle: "",
    legalText: "",
    legalCompany: "",
    legalDepartment1: "",
    legalDepartment2: "",
    legalStreet: "",
    legalCity: "",
    legalTelephone: "",
    legalMail: "",
    legalWebLink: "",
    legalWebLinkAlt: "",
    legalEditorial: "",
    legalAuthor: "",
    legalPhotoCredit: "",
    bodyFont: "'Inter', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    bodyFontSize: "10pt",
    customFonts: [],
    pageSize: "A4",
    orientation: "portrait",
    margins: { top: "25mm", right: "20mm", bottom: "25mm", left: "20mm" },
    pageBreakBeforeH1: false,
    pageBreakBeforeH2: false,
    pageBreakBeforeH3: false,
    includeMetadata: false,
    classificationText: "",
    classificationColor: "#c0392b",
    watermarkText: "",
    watermarkColor: "#000000",
    watermarkOpacity: 0.08,
    watermarkFontSize: "80pt",
    watermarkRotation: -45,
  };
}
