import type { PdfTheme } from "./types";

export const BUILTIN_THEMES: PdfTheme[] = [
  {
    id: "minimal",
    name: "Minimal",
    builtin: true,
    primaryColor: "#222222",
    accentColor: "#555555",
    
    h2FontSize: "",
    h2FontColor: "",
    h2FontStyle: "normal",
    h2FontWeight: "normal",
    h3FontSize: "",
    h3FontColor: "",
    h3FontStyle: "normal",
    h3FontWeight: "normal",
    h4FontSize: "",
    h4FontColor: "",
    h4FontStyle: "normal",
    h4FontWeight: "normal",
    h5FontSize: "",
    h5FontColor: "",
    h5FontStyle: "normal",
    h5FontWeight: "normal",
    h6FontSize: "",
    h6FontColor: "",
    h6FontStyle: "normal",
    h6FontWeight: "normal",
    
    logoPath: "",
    backgroundPath: "",
    showCover: false,
    showToc: false,
    tocTitle: "Table of Contents",
    tocH2FontSize: "",
    tocH2FontColor: "",
    tocH2FontStyle: "normal",
    tocH2FontWeight: "normal",
    tocH3FontSize: "",
    tocH3FontColor: "",
    tocH3FontStyle: "normal",
    tocH3FontWeight: "normal",
    tocH4FontSize: "",
    tocH4FontColor: "",
    tocH4FontStyle: "normal",
    tocH4FontWeight: "normal",
    
    showLof: false,
    lofTitle: "",
    lofKeyword: "",
    lofFontSize: "",
    lofFontColor: "",
    lofFontStyle: "normal",
    lofFontWeight: "normal",
    showLot: false,
    lotTitle: "",
    lotKeyword: "",
    lotFontSize: "",
    lotFontColor: "",
    lotFontStyle: "normal",
    lotFontWeight: "normal",
    
    title: "",
    titleFontSize: "",
    titleFontColor: "",
    titleFontStyle: "normal",
    titleFontWeight: "normal",
    subtitle: "",
    subtitleFontSize: "",
    subtitleFontColor: "",
    subtitleFontStyle: "normal",
    subtitleFontWeight: "normal",
    additionalContent: "",
    additionalContentFontSize: "",
    additionalContentFontColor: "",
    additionalContentFontStyle: "normal",
    additionalContentFontWeight: "normal",
    dedicatedCover: false,
    coverBackgroundPath: "",
    coverImagePath: "",
    coverInfoFields: [],
    protocolLike: false,
    protocolTitle: "",
    protocolCreatorText: "",
    protocolCreatorValue: "",
    protocolClientText: "",
    protocolClientValue: "",
    protocolClientParticipantText: "",
    protocolClientParticipantValue: "",
    protocolContractorText: "",
    protocolContractorValue: "",
    protocolContractorParticipantText: "",
    protocolContractorParticipantValue: "",
    protocolDateText: "",
    protocolDateValue: "",
    protocolLocationText: "",
    protocolLocationValue: "",
    showHeaderLogo: false,
    showHeaderOn1stPage: false,
    showFooterOn1stPage: false,
    headerLogoHeight: "10mm",
    headerText: "",
    header1FontSize: "",
    header1FontColor: "",
    header1FontStyle: "normal",
    header1FontWeight: "normal",
    headerText2: "",
    header2FontSize: "",
    header2FontColor: "",
    header2FontStyle: "normal",
    header2FontWeight: "normal",
    showPagination: true,
    paginationFormat: "{page} / {pages}",
    paginationFontSize: "",
    paginationFontColor: "",
    paginationFontStyle: "normal",
    paginationFontWeight: "normal",
    footerText: "",
    footerFontSize: "",
    footerFontColor: "",
    footerFontStyle: "normal",
    footerFontWeight: "normal",
    urlDisplay: "off",
    numberHeadings: false,
    showLegal: false,
    legalTitle: "",
    legalText: "",
    legalEditor: "",
    legalCompany: "",
    legalDepartment1: "",
    legalDepartment2: "",
    legalStreet: "",
    legalCity: "",
    legalTelephone: "",
    legalMail: "",
    legalWebLink: "",
    legalWebLinkAlt: "",
    legalEditorialText: "",
    legalEditorial: "",
    legalAuthorText: "",
    legalAuthor: "",
    legalPhotoCreditText: "",
    legalPhotoCredit: "",
    bodyFont: "'Georgia', 'Times New Roman', serif",
    codeFont: "'SF Mono', 'Fira Code', monospace",
    bodyFontSize: "11pt", 
    bodyFontStyle: "normal",
    bodyFontWeight: "normal",
    linkFontColor: "",
    linkFontStyle: "normal",
    linkFontWeight: "normal",
    linkFontUnderline: "underline",
    customFonts: [],
    pageSize: "A4",
    orientation: "portrait",
    margins: { top: "20mm", right: "20mm", bottom: "20mm", left: "20mm" },
    pageBreakBeforeH1: false,
    pageBreakBeforeH2: false,
    pageBreakBeforeH3: false,
    includeMetadata: false,
    classificationText: "",
    classificationColor: "#c0392b",
    watermarkText: "",
    watermarkColor: "#000000",
    watermarkOpacity: 0.08,
    watermarkFontSize: "80pt", 
    watermarkFontStyle: "normal",
    watermarkFontWeight: "normal",
    watermarkRotation: -45,
  },
];

/**
 * Deep-copy a theme into a new custom one. Deep, because `margins` and
 * `coverInfoFields` would otherwise be shared with the source theme and mutate
 * it from the editor.
 */
export function duplicateTheme(theme: PdfTheme): PdfTheme {
  const copy = JSON.parse(JSON.stringify(theme)) as PdfTheme;
  copy.id = "custom-" + Date.now();
  copy.name = `${theme.name} (copy)`;
  delete copy.builtin;
  return copy;
}

export function createBlankTheme(): PdfTheme {
  return {
    id: "custom-" + Date.now(),
    name: "New theme",
    primaryColor: "#333333",
    accentColor: "#666666",
    
    h2FontSize: "",
    h2FontColor: "",
    h2FontStyle: "normal",
    h2FontWeight: "normal",
    h3FontSize: "",
    h3FontColor: "",
    h3FontStyle: "normal",
    h3FontWeight: "normal",
    h4FontSize: "",
    h4FontColor: "",
    h4FontStyle: "normal",
    h4FontWeight: "normal",
    h5FontSize: "",
    h5FontColor: "",
    h5FontStyle: "normal",
    h5FontWeight: "normal",
    h6FontSize: "",
    h6FontColor: "",
    h6FontStyle: "normal",
    h6FontWeight: "normal",
    
    logoPath: "",
    backgroundPath: "",
    showCover: true,
    showToc: false,
    tocTitle: "Table of Contents",
    tocH2FontSize: "",
    tocH2FontColor: "",
    tocH2FontStyle: "normal",
    tocH2FontWeight: "normal",
    tocH3FontSize: "",
    tocH3FontColor: "",
    tocH3FontStyle: "normal",
    tocH3FontWeight: "normal",
    tocH4FontSize: "",
    tocH4FontColor: "",
    tocH4FontStyle: "normal",
    tocH4FontWeight: "normal",
    
    showLof: false,
    lofTitle: "",
    lofKeyword: "",
    lofFontSize: "",
    lofFontColor: "",
    lofFontStyle: "normal",
    lofFontWeight: "normal",
    showLot: false,
    lotTitle: "",
    lotKeyword: "",
    lotFontSize: "",
    lotFontColor: "",
    lotFontStyle: "normal",
    lotFontWeight: "normal",

    title: "",
    titleFontSize: "",
    titleFontColor: "",
    titleFontStyle: "normal",
    titleFontWeight: "normal",
    subtitle: "",
    subtitleFontSize: "",
    subtitleFontColor: "",
    subtitleFontStyle: "normal",
    subtitleFontWeight: "normal",
    additionalContent: "",
    additionalContentFontSize: "",
    additionalContentFontColor: "",
    additionalContentFontStyle: "normal",
    additionalContentFontWeight: "normal",
    dedicatedCover: false,
    coverBackgroundPath: "",
    coverImagePath: "",
    coverInfoFields: [],
    protocolLike: false,
    protocolTitle: "",
    protocolCreatorText: "",
    protocolCreatorValue: "",
    protocolClientText: "",
    protocolClientValue: "",
    protocolClientParticipantText: "",
    protocolClientParticipantValue: "",
    protocolContractorText: "",
    protocolContractorValue: "",
    protocolContractorParticipantText: "",
    protocolContractorParticipantValue: "",
    protocolDateText: "",
    protocolDateValue: "",
    protocolLocationText: "",
    protocolLocationValue: "",
    showHeaderLogo: false,
    showHeaderOn1stPage: false,
    showFooterOn1stPage: false,
    headerLogoHeight: "12mm",
    headerText: "",
    header1FontSize: "",
    header1FontColor: "",
    header1FontStyle: "normal",
    header1FontWeight: "normal",
    headerText2: "",
    header2FontSize: "",
    header2FontColor: "",
    header2FontStyle: "normal",
    header2FontWeight: "normal",
    showPagination: true,
    paginationFormat: "{page} / {pages}",
    paginationFontSize: "",
    paginationFontColor: "",
    paginationFontStyle: "normal",
    paginationFontWeight: "normal",
    footerText: "",
    footerFontSize: "",
    footerFontColor: "",
    footerFontStyle: "normal",
    footerFontWeight: "normal",
    urlDisplay: "off",
    numberHeadings: false,
    showLegal: false,
    legalTitle: "",
    legalText: "",
    legalEditor: "",
    legalCompany: "",
    legalDepartment1: "",
    legalDepartment2: "",
    legalStreet: "",
    legalCity: "",
    legalTelephone: "",
    legalMail: "",
    legalWebLink: "",
    legalWebLinkAlt: "",
    legalEditorialText: "",
    legalEditorial: "",
    legalAuthorText: "",
    legalAuthor: "",
    legalPhotoCreditText: "",
    legalPhotoCredit: "",
    bodyFont: "'Inter', sans-serif",
    codeFont: "'JetBrains Mono', monospace",
    bodyFontSize: "10pt",
    bodyFontStyle: "normal",
    bodyFontWeight: "normal",
    linkFontColor: "",
    linkFontStyle: "normal",
    linkFontWeight: "normal",
    linkFontUnderline: "underline",
    customFonts: [],
    pageSize: "A4",
    orientation: "portrait",
    margins: { top: "25mm", right: "20mm", bottom: "25mm", left: "20mm" },
    pageBreakBeforeH1: false,
    pageBreakBeforeH2: false,
    pageBreakBeforeH3: false,
    includeMetadata: false,
    classificationText: "",
    classificationColor: "#c0392b",
    watermarkText: "",
    watermarkColor: "#000000",
    watermarkOpacity: 0.08,
    watermarkFontSize: "80pt",
    watermarkFontStyle: "normal",
    watermarkFontWeight: "normal",
    watermarkRotation: -45,
  };
}
